# Generated by Django 5.0.6 on 2024-06-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0003_customeruser_auth_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customeruser",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
