# Generated by Django 5.0.6 on 2024-06-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0004_alter_customeruser_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="rating",
            field=models.IntegerField(default=0),
        ),
    ]
