# Generated by Django 5.0.6 on 2024-06-05 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wordgame", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attempt",
            name="user",
        ),
        migrations.RemoveField(
            model_name="attempt",
            name="word",
        ),
        migrations.AlterField(
            model_name="attempt",
            name="attempts",
            field=models.IntegerField(default=6),
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wordgame.word"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="attempt",
            name="game",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="wordgame.game",
            ),
            preserve_default=False,
        ),
    ]
