# Generated by Django 5.0.6 on 2024-06-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wordgame", "0002_remove_attempt_user_remove_attempt_word_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
