# Generated by Django 5.0.6 on 2024-06-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wordgame", "0003_game_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="win",
            field=models.BooleanField(default=False),
        ),
    ]
